# -*- coding: utf-8 -*-
"""LlamaIndexNeo4jMCP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_o0ix1dXgoxgI7U-NmcwBESWGqKTJRV
"""

!pip install --upgrade --quiet llama-index-core llama-index-llms-openai llama-index-tools-mcp llama-index-vector-stores-neo4jvector llama-index-embeddings-openai neo4j-mcp-server neo4j-agent-memory neo4j-agent-memory[openai] neo4j-agent-memory[llamaindex]

import subprocess

process = subprocess.Popen(
    [
        "neo4j-mcp-server",
        "--neo4j-uri", "neo4j+s://demo.neo4jlabs.com:7687",
        "--neo4j-database", "companies2",
        "--neo4j-transport-mode", "http",
        "--neo4j-read-only", "true",
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)

print("PID:", process.pid, "| Running:", process.poll() is None)

import base64
import json

from llama_index.core.agent.workflow import (
    AgentStream,
    FunctionAgent,
    ToolCall,
    ToolCallResult,
)
from llama_index.core.tools import FunctionTool
from llama_index.llms.openai import OpenAI
from llama_index.tools.mcp import BasicMCPClient, McpToolSpec

import os
from getpass import getpass

os.environ["OPENAI_API_KEY"] = getpass("OpenAI API key")

llm = OpenAI(model="gpt-5.4-mini")

# Credentials are passed via bearer auth
os.environ["NEO4J_USERNAME"] = "companies2"
os.environ["NEO4J_PASSWORD"] = "companies2"

credentials = base64.b64encode(f"{os.environ["NEO4J_USERNAME"]}:{os.environ["NEO4J_PASSWORD"]}".encode()).decode()

# Connect to MCP server (SSE, HTTP, or local process)
mcp_client = BasicMCPClient(
    "http://localhost:80/mcp",
    headers={"Authorization": f"Basic {credentials}"},
)

mcp_tool_spec = McpToolSpec(
    client=mcp_client,
)

# Get tools (async recommended)
tools = await mcp_tool_spec.to_tool_list_async()

async def run_handler(workflow, user_msg, memory):
  handler = workflow.run(user_msg=user_msg)#, memory=memory)
  async for event in handler.stream_events():
      if isinstance(event, ToolCall):
          print(f"\n🔧 TOOL CALL: {event.tool_name}")
          print(f"   └─ Args: {event.tool_kwargs}")

      elif isinstance(event, ToolCallResult):
          print(f"   └─ Result: {event.tool_output}")
          print("-"*50)

      elif isinstance(event, AgentStream):
          if event.delta:
              print(event.delta, end="", flush=True)

  response = await handler

from neo4j_agent_memory import MemoryClient, MemorySettings
#from neo4j_agent_memory.integrations.llamaindex import Neo4jLlamaIndexMemory

settings = MemorySettings(
    neo4j={"uri": "neo4j+s://02315c0c.databases.neo4j.io", "password": "zUXFEQXKZxfwAvHsE83tQL8wtfRTyEdTdBF2XCr_pnM"}
)

async with MemoryClient(
    settings=settings
) as client:
    # Use with LlamaIndex agent
    memory = Neo4jLlamaIndexMemory.from_defaults(session_id="wtf1234a", memory_client=client)
    system_prompt = """You are an agent that can search in neo4j for relevant information.
Use the get-schema before you execute any cypher queries"""

    workflow = FunctionAgent(
        tools=tools,
        llm=llm,
        system_prompt=system_prompt,
    )

    await run_handler(workflow, "Please list GDS graphs?", memory)#, memory=memory)
    #await run_handler(workflow, "what did I just ask", memory=memory)

